server:
  port: 8081

spring:
  application:
    name: spring-boot-rabbitmq

  rabbitmq:
    addresses: 192.168.8.175:5672,192.168.8.177:5672,192.168.8.178:5672
    username: admin
    password: admin
    publisher-returns: true
    publisher-confirm-type: correlated
    virtual-host: /
    listener:
      type: simple
      simple:
        acknowledge-mode: auto #确认模式
        prefetch: 1 #限制每次发送一条数据。
        concurrency: 3 #同一个队列启动几个消费者
        max-concurrency: 3 #启动消费者最大数量
        #重试策略相关配置
        retry:
          enabled: true #是否支持重试
          max-attempts: 5